In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
torch.__version__

'2.4.1+cpu'

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype , t1.shape , t1.ndim

(torch.float32, torch.Size([]), 0)

In [5]:
# vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [6]:
t2.ndim , t2.shape 

(1, torch.Size([4]))

In [7]:
t2.dtype == torch.float32

True

In [8]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])

t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [9]:
t3.ndim , t3.shape 

(2, torch.Size([3, 2]))

In [10]:
# 3-dimensional array 
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
    [[16,17,18],
     [19,20,21]]])

t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[16, 17, 18],
         [19, 20, 21]]])

In [11]:
t4.shape

torch.Size([2, 2, 3])

In [12]:
t4.ndim

3

### Tensor operations and gradients

In [13]:
# Create tensors 
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [14]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [15]:
# Compute derivatives
y.backward()

In [16]:
# Display gradients

print('dy/dx', x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


As expected , dy/dw has the same value as x, i.e.,3, and dy/db has the value 1. x.grad has value none because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient primarily used during dealing with vectors and metrices.

Autograd: Automatic Differentiation in PyTorch
Now, we will shift our focus on Autograd which is one of the most important topics in the PyTorch basics. The Autograd Module of PyTorch provides the automatic calculation of the gradients. It means that we do not need to calculate the gradients explicitly. You might be thinking what gradient is. So, the gradient represents the rate of change of functions with respect to parameters. This helps us to identify the difference between the predicted outputs and actual labels.

Let us take an example to understand this. Suppose, we create two tensors with names ‘x’ and ‘y’ and perform some computation on them. The result is stored in the variable ‘z.’ Then, we can call the backward() method to calculate the gradient of the z with respect to x and y. This is shown in the below code snippet.

In [2]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0,requires_grad=True)

# Perform computation
z = x**2 + y**3
print("Output tensor z:", z)

# Compute gradients
z.backward()

print("Gradient of x:", x.grad)
print("Gradient of y:", y.grad)

Output tensor z: tensor(31., grad_fn=<AddBackward0>)
Gradient of x: tensor(4.)
Gradient of y: tensor(27.)


In [17]:
x = np.array([[1,2],[3,4],[5,6.]])
x

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [18]:
x.dtype

dtype('float64')

We can convert a Numpy array to a Pytorch tensor using **torch.from_numpy**

In [19]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [20]:
print(x)
print('\n',y)

[[1. 2.]
 [3. 4.]
 [5. 6.]]

 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)


In [21]:
# Let's verify that both have the same data type
x.dtype , y.dtype

(dtype('float64'), torch.float64)

In [22]:
# Convert Pytorch tensor to a numpy array using .numpy() method

z = y.numpy()
z

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [1]:
import torch

# Create a tensor from a list
tensor1 = torch.tensor([1, 2, 3])
print("Tensor from list:", tensor1)

# Create a tensor of zeros with shape (2, 3)
tensor2 = torch.zeros(2, 3)
print("Tensor of zeros:", tensor2)

# Create a random tensor with shape (3, 2)
tensor3 = torch.rand(3, 2)
print("Random tensor:", tensor3)

# Performing operations on Tensors

# Addition
result_add = tensor1 + tensor2
print("Addition result:", result_add)


# Multiplication
result_mul = tensor2 * 5
print("Multiplication result:", result_mul)


# Matrix multiplication
result_matmul = torch.matmul(tensor2, tensor3)
print("Matrix multiplication result:", result_matmul)


Tensor from list: tensor([1, 2, 3])
Tensor of zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random tensor: tensor([[0.0728, 0.5602],
        [0.8688, 0.6627],
        [0.3699, 0.5217]])
Addition result: tensor([[1., 2., 3.],
        [1., 2., 3.]])
Multiplication result: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Matrix multiplication result: tensor([[0., 0.],
        [0., 0.]])
