In [292]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [293]:
torch.__version__

'2.4.1+cpu'

In [294]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [295]:
t1.dtype , t1.shape , t1.ndim

(torch.float32, torch.Size([]), 0)

In [296]:
# vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [297]:
t2.ndim , t2.shape 

(1, torch.Size([4]))

In [298]:
t2.dtype == torch.float32

True

In [299]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])

t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [300]:
t3.ndim , t3.shape 

(2, torch.Size([3, 2]))

In [301]:
# 3-dimensional array 
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
    [[16,17,18],
     [19,20,21]]])

t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[16, 17, 18],
         [19, 20, 21]]])

In [302]:
t4.shape

torch.Size([2, 2, 3])

In [303]:
t4.ndim

3

### Tensor operations and gradients

In [304]:
# Create tensors 
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [305]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [306]:
# Compute derivatives
y.backward()

In [307]:
# Display gradients

print('dy/dx', x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


As expected , dy/dw has the same value as x, i.e.,3, and dy/db has the value 1. x.grad has value none because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient primarily used during dealing with vectors and metrices.

Autograd: Automatic Differentiation in PyTorch
Now, we will shift our focus on Autograd which is one of the most important topics in the PyTorch basics. The Autograd Module of PyTorch provides the automatic calculation of the gradients. It means that we do not need to calculate the gradients explicitly. You might be thinking what gradient is. So, the gradient represents the rate of change of functions with respect to parameters. This helps us to identify the difference between the predicted outputs and actual labels.

Let us take an example to understand this. Suppose, we create two tensors with names ‘x’ and ‘y’ and perform some computation on them. The result is stored in the variable ‘z.’ Then, we can call the backward() method to calculate the gradient of the z with respect to x and y. This is shown in the below code snippet.

In [308]:
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0,requires_grad=True)

# Perform computation
z = x**2 + y**3
print("Output tensor z:", z)

# Compute gradients
z.backward()

print("Gradient of x:", x.grad)
print("Gradient of y:", y.grad)

Output tensor z: tensor(31., grad_fn=<AddBackward0>)
Gradient of x: tensor(4.)
Gradient of y: tensor(27.)


In [309]:
x = np.array([[1,2],[3,4],[5,6.]])
x

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [310]:
x.dtype

dtype('float64')

We can convert a Numpy array to a Pytorch tensor using **torch.from_numpy**

In [311]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [312]:
print(x)
print('\n',y)

[[1. 2.]
 [3. 4.]
 [5. 6.]]

 tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)


In [313]:
# Let's verify that both have the same data type
x.dtype , y.dtype

(dtype('float64'), torch.float64)

In [314]:
# Convert Pytorch tensor to a numpy array using .numpy() method

z = y.numpy()
z

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [315]:
import torch

# Create a tensor from a list
tensor1 = torch.tensor([1, 2, 3])
print("Tensor from list:", tensor1)

# Create a tensor of zeros with shape (2, 3)
tensor2 = torch.zeros(2, 3)
print("Tensor of zeros:", tensor2)

# Create a random tensor with shape (3, 2)
tensor3 = torch.rand(3, 2)
print("Random tensor:", tensor3)

# Performing operations on Tensors

# Addition
result_add = tensor1 + tensor2
print("Addition result:", result_add)


# Multiplication
result_mul = tensor2 * 5
print("Multiplication result:", result_mul)


# Matrix multiplication
result_matmul = torch.matmul(tensor2, tensor3)
print("Matrix multiplication result:", result_matmul)


Tensor from list: tensor([1, 2, 3])
Tensor of zeros: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Random tensor: tensor([[0.6120, 0.5887],
        [0.1252, 0.7219],
        [0.5881, 0.6493]])
Addition result: tensor([[1., 2., 3.],
        [1., 2., 3.]])
Multiplication result: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Matrix multiplication result: tensor([[0., 0.],
        [0., 0.]])


## Introduction to Linear Regression

In this tutorial, we'll discuss one of the foundational algorithms in machine learning: *Linear regression*. We'll create a model that predicts crop yields for apples and oranges (*target variables*) by looking at the average temperature, rainfall, and humidity (*input variables or features*) in a region. Here's the training data:

![linear-regression-training-data](https://i.imgur.com/6Ujttb4.png)

In a linear regression model, each target variable is estimated to be a weighted sum of the input variables, offset by some constant, known as a bias :

```
yield_apple  = w11 * temp + w12 * rainfall + w13 * humidity + b1
yield_orange = w21 * temp + w22 * rainfall + w23 * humidity + b2
```

Visually, it means that the yield of apples is a linear or planar function of temperature, rainfall and humidity:

![linear-regression-graph](https://i.imgur.com/4DJ9f8X.png)

The *learning* part of linear regression is to figure out a set of weights `w11, w12,... w23, b1 & b2` using the training data, to make accurate predictions for new data. The _learned_ weights will be used to predict the yields for apples and oranges in a new region using the average temperature, rainfall, and humidity for that region.

We'll _train_ our model by adjusting the weights slightly many times to make better predictions, using an optimization technique called *gradient descent*.

Either use dot e.g 4. or mentioned dtype for getting float value here

In [316]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [317]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

We've separated the input and target variables because we'll operate on them separately. Also, we've created numpy arrays, because this is typically how you would work with training data: read some CSV files as numpy arrays, do some processing, and then convert them to PyTorch tensors.

Let's convert the arrays to PyTorch tensors.

In [318]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## Linear regression model from scratch

The weights and biases (`w11, w12,... w23, b1 & b2`) can also be represented as matrices, initialized as random values. The first row of `w` and the first element of `b` are used to predict the first target variable, i.e., yield of apples, and similarly, the second for oranges.

In [319]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-0.0485, -1.3688,  0.5538],
        [-2.1060,  0.3984, -0.0281]], requires_grad=True)
tensor([ 0.0046, -0.6011], requires_grad=True)


`torch.randn` creates a tensor with the given shape, with elements picked randomly from a [normal distribution](https://en.wikipedia.org/wiki/Normal_distribution) with mean 0 and standard deviation 1.

Our *model* is simply a function that performs a matrix multiplication of the `inputs` and the weights `w` (transposed) and adds the bias `b` (replicated for each observation).

![matrix-mult](https://i.imgur.com/WGXLFvA.png)

We can define the model as follows:

In [320]:
w.t()

tensor([[-0.0485, -2.1060],
        [-1.3688,  0.3984],
        [ 0.5538, -0.0281]], grad_fn=<TBackward0>)

In [321]:
inputs @ w.t()

tensor([[ -71.4320, -128.2537],
        [ -89.4187, -158.3855],
        [-155.5108, -131.4644],
        [ -43.3098, -198.7226],
        [ -95.9799, -109.0339]], grad_fn=<MmBackward0>)

In [322]:
inputs @w.t() + b

tensor([[ -71.4273, -128.8549],
        [ -89.4141, -158.9866],
        [-155.5061, -132.0655],
        [ -43.3051, -199.3237],
        [ -95.9753, -109.6351]], grad_fn=<AddBackward0>)

In [323]:
def model(x):
    return x @ w.t() + b

`@` represents matrix multiplication in PyTorch, and the `.t` method returns the transpose of a tensor.

The matrix obtained by passing the input data into the model is a set of predictions for the target variables.

In [324]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -71.4273, -128.8549],
        [ -89.4141, -158.9866],
        [-155.5061, -132.0655],
        [ -43.3051, -199.3237],
        [ -95.9753, -109.6351]], grad_fn=<AddBackward0>)


Let's compare the predictions of our model with the actual targets.

In [325]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


You can see a big difference between our model's predictions and the actual targets because we've initialized our model with random weights and biases. Obviously, we can't expect a randomly initialized model to *just work*.

## Loss function

Before we improve our model, we need a way to evaluate how well our model is performing. We can compare the model's predictions with the actual targets using the following method:

* Calculate the difference between the two matrices (`preds` and `targets`).
* Square all elements of the difference matrix to remove negative values.
* Calculate the average of the elements in the resulting matrix.

The result is a single number, known as the **mean squared error** (MSE).

In [326]:
# diff = preds - targets
# torch.sum(diff*diff) -> show sum
# diff.numel() - > show length

In [327]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

`torch.sum` returns the sum of all the elements in a tensor. The `.numel` method of a tensor returns the number of elements in a tensor. Let's compute the mean squared error for the current predictions of our model.

In [328]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(45000.7148, grad_fn=<DivBackward0>)


Here’s how we can interpret the result: *On average, each element in the prediction differs from the actual target by the square root of the loss*. And that’s pretty bad, considering the numbers we are trying to predict are themselves in the range 50–200. The result is called the *loss* because it indicates how bad the model is at predicting the target variables. It represents information loss in the model: the lower the loss, the better the model.

## Compute gradients

With PyTorch, we can automatically compute the gradient or derivative of the loss w.r.t. to the weights and biases because they have `requires_grad` set to `True`. We'll see how this is useful in just a moment.

In [329]:
# Compute gradients
loss.backward()

The gradients are stored in the `.grad` property of the respective tensors. Note that the derivative of the loss w.r.t. the weights matrix is itself a matrix with the same dimensions.

In [330]:
# Gradients for weights

print(w)
print(w.grad)

tensor([[-0.0485, -1.3688,  0.5538],
        [-2.1060,  0.3984, -0.0281]], requires_grad=True)
tensor([[-13816.4668, -16445.5293,  -9730.3594],
        [-20223.3438, -20766.3516, -13062.4268]])


In [331]:
print(b)
print(b.grad)

tensor([ 0.0046, -0.6011], requires_grad=True)
tensor([-167.3256, -237.7731])


## Adjust weights and biases to reduce the loss

The loss is a [quadratic function](https://en.wikipedia.org/wiki/Quadratic_function) of our weights and biases, and our objective is to find the set of weights where the loss is the lowest. If we plot a graph of the loss w.r.t any individual weight or bias element, it will look like the figure shown below. An important insight from calculus is that the gradient indicates the rate of change of the loss, i.e., the loss function's [slope](https://en.wikipedia.org/wiki/Slope) w.r.t. the weights and biases.

If a gradient element is **positive**:

* **increasing** the weight element's value slightly will **increase** the loss
* **decreasing** the weight element's value slightly will **decrease** the loss

![postive-gradient](https://i.imgur.com/WLzJ4xP.png)

If a gradient element is **negative**:

* **increasing** the weight element's value slightly will **decrease** the loss
* **decreasing** the weight element's value slightly will **increase** the loss

![negative=gradient](https://i.imgur.com/dvG2fxU.png)

The increase or decrease in the loss by changing a weight element is proportional to the gradient of the loss w.r.t. that element. This observation forms the basis of _the gradient descent_ optimization algorithm that we'll use to improve our model (by _descending_ along the _gradient_).

We can subtract from each weight element a small quantity proportional to the derivative of the loss w.r.t. that element to reduce the loss slightly.

In [332]:
w
w.grad

tensor([[-13816.4668, -16445.5293,  -9730.3594],
        [-20223.3438, -20766.3516, -13062.4268]])

In [333]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

We multiply the gradients with a very small number (`10^-5` in this case) to ensure that we don't modify the weights by a very large amount. We want to take a small step in the downhill direction of the gradient, not a giant leap. This number is called the *learning rate* of the algorithm.

We use `torch.no_grad` to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

In [334]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(45000.7148, grad_fn=<DivBackward0>)


Before we proceed, we reset the gradients to zero by invoking the `.zero_()` method. We need to do this because PyTorch accumulates gradients. Otherwise, the next time we invoke `.backward` on the loss, the new gradient values are added to the existing gradients, which may lead to unexpected results.

In [335]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


## Train the model using gradient descent

As seen above, we reduce the loss and improve our model using the gradient descent optimization algorithm. Thus, we can _train_ the model using the following steps:

1. Generate predictions

2. Calculate the loss

3. Compute gradients w.r.t the weights and biases

4. Adjust the weights by subtracting a small quantity proportional to the gradient

5. Reset the gradients to zero

Let's implement the above step by step.

In [340]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ -46.1371,  -94.5592],
        [ -56.1399, -113.9466],
        [-115.8035,  -79.0657],
        [ -18.5388, -164.9309],
        [ -63.8413,  -66.5992]], grad_fn=<AddBackward0>)


In [341]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(30732.8242, grad_fn=<DivBackward0>)


In [342]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-11202.1328, -13627.0225,  -7993.2568],
        [-16685.1953, -16971.6230, -10719.1650]])
tensor([-136.2922, -195.8203])


Let's update the weights and biases using the gradients computed above.

In [343]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

We multiply the gradients with a very small number (`10^-5` in this case) to ensure that we don't modify the weights by a very large amount. We want to take a small step in the downhill direction of the gradient, not a giant leap. This number is called the *learning rate* of the algorithm.

We use `torch.no_grad` to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

After we have updated the weights, we reset the gradients back to zero to avoid affecting any future computations

Let's take a look at the new weights and biases.

In [344]:
print(w)
print(b)

tensor([[ 0.2017, -1.0680,  0.7310],
        [-1.7369,  0.7758,  0.2097]], requires_grad=True)
tensor([ 0.0077, -0.5968], requires_grad=True)


In [345]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(21112.8281, grad_fn=<DivBackward0>)


We have already achieved a significant reduction in the loss merely by adjusting the weights and biases slightly using gradient descent.

## Train for multiple epochs

To reduce the loss further, we can repeat the process of adjusting the weights and biases using the gradients multiple times. Each iteration is called an _epoch_. Let's train the model for 100 epochs.

In [346]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [347]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(367.5631, grad_fn=<DivBackward0>)


The loss is now much lower than its initial value. Let's look at the model's predictions and compare them with the targets.

In [348]:
# Predictions
preds

tensor([[ 63.8288,  66.2026],
        [ 91.3925,  95.4592],
        [ 87.0894, 151.4098],
        [ 60.2739,  13.4720],
        [ 95.0310, 123.6959]], grad_fn=<AddBackward0>)

In [349]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

The predictions are now quite close to the target variables. We can get even better results by training for a few more epochs.