In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
torch.__version__

'2.4.1+cpu'

In [4]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [5]:
t1.dtype , t1.shape , t1.ndim

(torch.float32, torch.Size([]), 0)

In [6]:
# vector
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [7]:
t2.ndim , t2.shape 

(1, torch.Size([4]))

In [8]:
t2.dtype == torch.float32

True

In [9]:
# Matrix
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])

t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [10]:
t3.ndim , t3.shape 

(2, torch.Size([3, 2]))

In [11]:
# 3-dimensional array 
t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
    [[16,17,18],
     [19,20,21]]])

t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[16, 17, 18],
         [19, 20, 21]]])

In [12]:
t4.shape

torch.Size([2, 2, 3])

In [13]:
t4.ndim

3

### Tensor operations and gradients

In [14]:
# Create tensors 
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [15]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [16]:
# Compute derivatives
y.backward()

In [17]:
# Display gradients

print('dy/dx', x.grad)
print('dy/dw',w.grad)
print('dy/db',b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


As expected , dy/dw has the same value as x, i.e.,3, and dy/db has the value 1. x.grad has value none because x doesn't have requires_grad set to True.

The "grad" in w.grad is short for gradient, which is another term for derivative. The term gradient primarily used during dealing with vectors and metrices.